version: 1.0.{build}
image: macos-sonoma  # Use macOS Sonoma image (or the latest available)

install:
  - cmd: brew update
  - cmd: brew install python  # Ensure Python is installed
  - cmd: python3 -m venv venv  # Create a Python virtual environment
  - cmd: pip install --upgrade pip  # Upgrade pip
  - cmd: pip install torrentp  # Install the 'torrentp' library (ensure it’s in the requirements)

# Optional: Upload artifacts if needed (such as logs or output)
artifacts:
  - path: build_output/
    name: Build Artifacts
