version: 1.0.{build}

# Using Windows with Visual Studio 2019
image: Visual Studio 2019

# Set the build mode to "Script" instead of "MSBuild"
build_script:
  - echo "Preparing environment..."

  # Install Deluge via Chocolatey
  - choco install deluge -y  # Install Deluge via Chocolatey

  # Start the Deluge daemon
  - echo "Starting Deluge daemon"
  - start /B deluged  # Start the Deluge daemon in the background
  - timeout /t 10  # Wait for it to start (timeout command for Windows)

  # Set seeding time to 0
  - echo "Setting seeding_time to 0 to disable seeding"
  - deluge-console config -s seeding_time 0

  # Adding a torrent using a magnet link
  - echo "Adding torrent via magnet link"
  - deluge-console add "magnet:?xt=urn:btih:34F2A1FA5CD593C394C6E5B5B83B92A7165EA9A9&dn=Learn+Python+In+A+Week+And+Master+It&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce"

  # Adding .torrent files if available
  - echo "Checking for .torrent files to add..."
  - |
    for %%f in (torrents\*.torrent) do (
      echo "Adding torrent: %%f"
      deluge-console add "%%f"
    )

  # Stop the Deluge daemon
  - echo "Stopping Deluge daemon"
  - deluge-console quit
